CODE alien.ulx
PICTURE Nave1_jpg res/img/nave1.jpg
PICTURE Nave1_Trueno_jpg res/img/nave1_trueno.jpg
PICTURE Nave2_jpg res/img/nave2.jpg
PICTURE Nave2_Trueno_jpg res/img/nave2_trueno.jpg
PICTURE Exterior1_jpg res/img/exterior1.jpg
PICTURE Exterior3_jpg res/img/exterior3.jpg
PICTURE Junto_Procesador_jpg res/img/junto_procesador.jpg
PICTURE Junto_Procesador_Abierto_jpg res/img/junto_procesador_abierto.jpg
PICTURE Junto_Puerta_jpg res/img/junto_puerta.jpg
PICTURE Junto_Puerta_Abierta_jpg res/img/junto_puerta_abierta.jpg
PICTURE Procesador_jpg res/img/procesador.jpg
PICTURE Entrada_jpg, res/img/entrada.jpg
PICTURE Entrada_Sellada_jpg res/img/entrada_sellada.jpg
PICTURE Laberinto_Oeste_jpg res/img/laberinto_oeste.jpg
PICTURE Laberinto_Este_jpg res/img/laberinto_este.jpg
PICTURE Aula_jpg res/img/aula.jpg
PICTURE Balcon_jpg res/img/balcon.jpg
PICTURE Seguridad_jpg res/img/seguridad.jpg
PICTURE Laboratorio_jpg res/img/laboratorio.jpg
PICTURE Enfermeria_jpg res/img/enfermeria.jpg
PICTURE Cocina_jpg res/img/cocina.jpg
PICTURE Comedor_jpg res/img/comedor.jpg
PICTURE Despensa_jpg res/img/despensa.jpg
PICTURE Oficina_jpg res/img/oficina.jpg
PICTURE Ventilacion1_jpg res/img/ventilacion1.jpg
PICTURE Hueco_Techo_jpg res/img/hueco_techo.jpg
PICTURE Ascensor_Emergencia_jpg res/img/ascensor_emergencia.jpg
PICTURE Emergencia_Pasillo_jpg res/img/emergencia_pasillo.jpg
PICTURE Emergencia_Oeste_jpg res/img/emergencia_oeste.jpg
PICTURE Emergencia_Este_jpg res/img/emergencia_este.jpg
PICTURE Robot_jpg res/img/robot.jpg
PICTURE Alien_Rapta_Jason_jpg res/img/alien_rapta_jason.jpg
PICTURE Alien_Mata_jpg res/img/alien_mata.jpg
PICTURE Logo_Alpha_Aventuras_jpg res/img/logo_alpha_aventuras.jpg
PICTURE Logo_Alpha_Aventuras_Corto_jpg res/img/logo_alpha_aventuras_corto.jpg
PICTURE Oscuridad_jpg res/img/oscuridad.jpg
PICTURE Logo_Alien_jpg res/img/logo_alien.jpg
PICTURE A_png res/img/a.png
PICTURE AI_png res/img/ai.png
PICTURE AIN_png res/img/ain.png
PICTURE AIEN_png res/img/aien.png
PICTURE ALIEN_Sin_Puntos_png res/img/alien_sin_puntos.png
PICTURE Puntos_png res/img/puntos.png
PICTURE Fondo_Blanco_jpg res/img/fondo_blanco.jpg
SOUND Intro_ogg res/snd/intro.ogg
SOUND Teletipo_ogg res/snd/teletipo.ogg
SOUND Detector1_ogg res/snd/detector1.ogg
SOUND Detector2_ogg res/snd/detector2.ogg
SOUND Detector3_ogg res/snd/detector3.ogg
SOUND Detector4_ogg res/snd/detector4.ogg
SOUND Detector5_ogg res/snd/detector5.ogg
SOUND Sirena_ogg res/snd/sirena.ogg
SOUND Bisturi_ogg res/snd/bisturi.ogg
SOUND Transmisor_ogg res/snd/transmisor.ogg
SOUND Nave_ogg res/snd/nave.ogg
SOUND Lluvia_ogg res/snd/lluvia.ogg
SOUND Maquinaria_ogg res/snd/maquinaria.ogg
SOUND Junto_Procesador_ogg res/snd/junto_procesador.ogg
SOUND Pasillo_ogg res/snd/pasillo.ogg
SOUND Balcon_ogg res/snd/balcon.ogg
SOUND Estancia_ogg res/snd/estancia.ogg
SOUND Montacargas_ogg res/snd/montacargas.ogg
SOUND Ventilacion_ogg res/snd/ventilacion.ogg
SOUND Vaina_ogg res/snd/vaina.ogg
SOUND Grito_Jason_ogg res/snd/grito_jason.ogg
SOUND Grito_Jugador_ogg res/snd/grito_jugador.ogg
SOUND Rugido_ogg res/snd/rugido.ogg
SOUND Arana_Corto_ogg res/snd/arana_corto.ogg
SOUND Arana_Largo_ogg res/snd/arana_largo.ogg
SOUND Arana_Chillido_ogg res/snd/arana_chillido.ogg
SOUND Trueno_ogg res/snd/trueno.ogg
SOUND Explosion_ogg res/snd/explosion.ogg
SOUND Gota_Oscura_ogg res/snd/gota_oscura.ogg
SOUND Gotas_Agua_ogg res/snd/gotas_agua.ogg
SOUND Cueva_Oscura_ogg res/snd/cueva_oscura.ogg
SOUND Monstruo_ogg res/snd/monstruo.ogg
SOUND Descompresion_ogg res/snd/descompresion.ogg
SOUND Puerta1_ogg res/snd/puerta1.ogg
SOUND Puerta2_ogg res/snd/puerta2.ogg
SOUND Tic_ogg res/snd/tic.ogg
SOUND Chispazo_ogg res/snd/chispazo.ogg
SOUND Robot_ogg res/snd/robot.ogg
SOUND Tension_ogg res/snd/tension.ogg
SOUND Rotura_ogg res/snd/rotura.ogg

